README.md, source/handleAssertions/makeDiagnostic.ts, source/parser.ts, source/tsdLite.ts, source/types.ts, tests/api.test.ts, tests/assignable.test.ts, tests/deprecated.test.ts, tests/error.test.ts, tests/identical.test.ts, tests/syntax-errors.test.ts, tests/tsconfig.json, tests/utils.ts
Return diagnostics in ts-style. Less logic duplication in this library and more flexibility for the end user.
=> feat!: return ts-style diagnostics

source/handleAssertions/assignable.ts, source/handleAssertions/deprecated.ts, source/handleAssertions/identical.ts, source/handleAssertions/index.ts, source/handleAssertions/makeTsdResult.ts, source/index.ts, source/tsdLite.ts, source/types.ts, tests/api.test.ts, tests/assignable.test.ts, tests/compilerOptions.test.ts, tests/deprecated.test.ts, tests/error.test.ts, tests/identical.test.ts, tests/promises.test.ts, tests/syntax-errors.test.ts, tests/utils.ts
Returning `tsdResult` makes it more clear that this is the result. Less overlap with diagnostics of TypeScript compiler.
=> refactor!: return `tsdResult` instead of `diagnostics`

README.md, cspell.config.json, source/tsdLite.ts, tests/compilerOptions.test.ts, tests/syntax-errors.test.ts, tests/utils.ts
If a test file has syntax errors, the tsd result might be unpredictable. Better to fail early.
=> refactor!: fail early if syntax errors are found

.yarn/versions/b0a95d05.yml, CHANGELOG.md, README.md, source/tsdLite.ts, source/utils/TsdError.ts, source/utils/index.ts, source/utils/isDiagnosticWithLocation.ts, source/utils/resolveCompilerOptions.ts, tests/api.test.ts, tests/compilerOptions-errors/tsconfig.json, tests/compilerOptions.test.ts, tests/syntax-errors.test.ts, tests/utils.ts
Throw `TsdError` (instead of returning `tsdErrors`) if:
- TS compiler encountered an error while parsing `tsconfig.json`;
- or found a syntax error while compiling the code.
=> feat!: throw instead of returning tsdErrors

.yarn/versions/a866028a.yml, CHANGELOG.md, README.md, source/tsdLite.ts, source/types.ts, tests/utils.ts
Do not add flattened `message` to `tsdResults` object. `messageText` is there already and should be used instead.
=> refactor!: do not add message

.yarn/versions/11126c96.yml, CHANGELOG.md, source/parser.ts
Parser will skip declaration files while extracting assertions. Test files should have all the assertions.
=> perf: skip declaration files

.yarn/versions/bac0538f.yml, CHANGELOG.md, source/tsdLite.ts, source/utils/resolveCompilerOptions.ts
Fixing regression. Should use default compiler options in case `tsconfig.json` is not found.
=> fix: resolve compiler options correctly in case tsconfig.json is not found

.eslintrc.json, .yarn/versions/ea0f85d4.yml, source/assertions.ts, source/handleAssertions/assignable.ts, source/handleAssertions/identical.ts, source/handleAssertions/index.ts, tests/api.test.ts, tests/assignable.test.ts, tests/expectAssignable/index.test.ts, tests/expectNotAssignable/index.test.ts, tests/expectNotType/index.test.ts, tests/expectType/index.test.ts, tests/identical.test.ts
Adds assertion logic for `expectAssignable` and `expectType` instead of a fall back on semantic diagnostics.
=> fix!: improve expectType and expectAssignable

.yarn/versions/e89abd7c.yml, source/silenceError.ts, tests/expectError/index.test.ts
Adding "ts2542: Index signature in type '{0}' only permits reading" to the list of expected errors.
=> fix: add `ts2542` to the list of expected errors

.yarn/versions/325c64cf.yml, source/silenceError.ts, tests/expectError/index.test.ts
Adding "ts2366: Function lacks ending return statement and return type does not include 'undefined'" to the list of expected errors.
=> fix: add ts2366 to the list of expected errors

.yarn/versions/49f57b58.yml, source/index.ts
Exposing `TsdResult` type is useful for type checking in third party implementations.
=> fix: expose `TsdResult` type

package.json
This changes that registries like npmjs will make it easier for finding the source of the project
will change from:
to something like typegoose has:
(only that for this project both links would be similar)
=> Add properties `bugs` and `homepage` and modify `repository`

.github/workflows/node-ci.yml, .yarn/versions/5e378b43.yml
Dropping Node v12. The just released Jest v29 does not support it anymore time to move on.
=> chore: drop Node v12 support

.github/workflows/node-ci.yml
Adding Node.js v19 to CI workflow.
=> chore(ci): run tests on Node.js v19

README.md
Hello there, I was looking for a non-jest based way of running `test-d` files in a TS project and couldn't find anything so I put together a small standalone library with basic TAP output.
https://github.com/asd-xiv/tsd-lite-cli
I created a PR to add a link to it in your docs :vulcan_salute:
=> docs: add reference to "tsd-lite-cli" 3rd party library

.yarn/versions/438b2de9.yml, source/silenceError.ts, tests/compilerOptions-exactOptionalPropertyTypes/index.d.ts, tests/compilerOptions-exactOptionalPropertyTypes/index.test.ts, tests/compilerOptions-exactOptionalPropertyTypes/tsconfig.json, tests/compilerOptions.test.ts
Adding error related with `compilerOptions.exactOptionalPropertyTypes` to the list of expected errors.
=> fix: add ts2375, ts2379 and ts2412 to the list of expected errors

.yarn/versions/786b7b56.yml, package.json
Currently `engines` has incorrect declaration.
=> chore: declare Node.js v14 as lowest supported version

source/handleAssertions/identical.ts, tests/api.test.ts, tests/identical.test.ts
The `isTypeAssignableTo` checks are redundant before `isTypeIdenticalTo`. Having straight forward error message is also good idea.
=> refactor: remove redundant checks

.yarn/versions/503df5b8.yml, package.json, yarn.lock
It is time to drop support for `@tsd/typescript` v3.x; and to add support for soon to be released v5.x.
=> chore: drop support for `@tsd/typescript` v3.x and add support for v5.x

.github/workflows/node-ci.yml
=> chore(ci): run tests on Node.js v20

.github/workflows/node-ci.yml, .yarn/versions/a422cf76.yml, package.json
Dropping support for Node.js v14 and v19, because these are EOL (reference: the [release schedule](https://github.com/nodejs/release#release-schedule)).
=> chore: drop support for Node.js v14 and v19

package.json, tests/compilerOptions-errors/tsconfig.json, tests/tsconfig.json, tsconfig.json, yarn.lock
Use `@tsconfig/node16` base to simplify TSConfig files.
=> chore: use `@tsconfig/node16` base

.yarn/versions/8c05e69a.yml, source/assertions.ts, tests/error.test.ts, tests/expectError/index.test.ts
Removing the `expectError()` assertion type argument:
1. Its functionality is questionable, because it does the same as `expectNotAssignable()` (to be precise, `expectNotAssignable()` exposed from `'tsd-lite'` ~~does this job better~~ is more predictable).
2. When `expectNotAssignable()` is used, the test becomes easier to understand.
3. The usage of the type argument is not documented by the authors of `tsd`.
---
Migration. Simply use `expectNotAssignable()` instead:
```diff
- expectError<PackageJSON>({
+ expectNotAssignable<PackageJSON>({
filter: () => {},
});
```
=> refactor!: remove the confusing `expectError()` type argument

package.json, yarn.lock
Adding the missing `'@types/node'` dev dependency. (Also ran `npx sort-package-json`.)
=> chore: add missing '@types/node' dev dependency

source/tsdLite.ts, source/utils/TsdError.ts, source/utils/resolveCompilerOptions.ts
The constructor of the `TsdError` class can be simplified for more flexible usage.
=> refactor: simplify constructor of the `TsdError` class

.yarn/versions/60ec5113.yml, source/parser.ts
This was overlooked in the initial release. `'tsd-lite'` must throw if an import from `'tsd'` package is encountered, because:
1. The typings and shape of testing APIs differ between the packages.
2. The APIs of `'tsd-lite'` do not suffer from bug like https://github.com/SamVerschueren/tsd/issues/142.
3. `'tsd-lite'` does not ship `'@tsd/typescript'` which is installed by `'tsd'`, but that is useless waste of disk space.
=> fix: error on imports from `'tsd'` package
